config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :games, only: [:index, :show, :create, :new] do
    member do
      put :join
    end

    resources :players, only: [:new, :create]

    resources :squares, only: [] do
      member do
        put :claim
      end
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  validates :board_size,
            presence: true
  validates :min_players,
            presence: true
  validates :max_players,
            presence: true
  validates :state,
            presence: true

  STATES = %w(not_started started ended).freeze
  self.per_page = 10

  has_many :players, dependent: :destroy
  has_many :squares, dependent: :destroy

  scope :ordered, -> { order(:created_at) }

  scope :for_user, -> (current_user_id) {
    joins(:players).where(players: { user_id: current_user_id })
  }

  def add_player(user, player_name)
    if self.players_count == self.max_players
      return {
        success: false,
        result: 'max players reached for the game'
      }
    else
      player = self.players.create(user: user, name: player_name)

      return {
        success: true,
        result: player
      }
    end
  end

  def player_in_game?(user_id)
    players = self.players

    players.map(&:user).map(&:id).include?(user_id)
  end

  def current_player(user)
    self.players.find { |player| player.user == user }
  end

  def over?
    self.state == 'ended'
  end

  def started?
    self.state == 'started'
  end

  def start!
    case self.state
    when 'not_started'
      self.state = STATES.second
      self.save!
      return {
        success: true,
        message: 'Game has started'
      }
    when 'ended'
      return {
        success: false,
        message: 'Cannot transition from ended to started'
      }
    end
  end

  def end!
    case self.state
    when 'started'
      self.state = STATES.last
      self.save!
      return {
        success: true,
        message: 'Game has ended'
      }
    when 'not_started'
      return {
        success: false,
        message: 'Game has not started'
      }
    end
  end

  def square_claimed_by(square_id)
    square = self.squares.find { |square| square.id == square_id }
    self.players.find { |player| player.id == square.player_id }
  end

  def winner
    self.players.find { |player| player.id == self.winner_id }
  end

  def assign_winner
    winner_id, _ = self.squares.inject(Hash.new(0)) {|h, v| h[v.player_id] += 1; h}.max_by{ |k, v| v }
    self.winner_id = winner_id
    self.save
  end

  def unclaimed_squares
    self.squares.select{ |square| square.player_id.nil? }.map(&:id)
  end

  def score(player_id)
    self.squares.select { |square| square.player_id == player_id.to_i }.count
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all.ordered.paginate(page: params[:page])
  end

  def new
    @game = Game.new
  end

  def show
    @game = game

    if !game.player_in_game?(current_user.id)
      flash[:notice] = "You have not joined the game: #{game.id} yet"
      redirect_to games_path
    end

    @player = game.current_player(current_user)
    @players = game.players.ordered
  end

  def create
    @game = Game.new(board_size: board_size,
                     min_players: min_players,
                     max_players: max_players,
                     blockage_time: blockage_time)

    (1..board_size).each { |i| @game.squares.build(number: i, game: @game) }

    if @game.save
      @game.add_player(current_user, player_name)
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def join
    if game.players_count == game.max_players
      flash[:alert] = 'max players reached for the game'
      render :index
    elsif game.player_in_game?(current_user.id)
      redirect_to game_path(game)
    else
      redirect_to new_game_player_path(game)
    end
  end

  private

  def game_params
    params.require(:game).permit(:player_name,
                                 :board_size,
                                 :min_players,
                                 :max_players,
                                 :blockage_time)
  end

  def board_size
    game_params[:board_size] || 10
  end

  def min_players
    game_params[:min_players] || 2
  end

  def max_players
    game_params[:max_players] || 4
  end

  def player_name
    game_params[:player_name]
  end

  def blockage_time
    game_params[:blockage_time] || 1
  end

  def game
    @_game ||= Game.includes(:squares, :players).find(params[:id])
  end
end

app/views/games/index.html.haml
.pure-u-1-3
.pure-u-1-3
  - @games.ordered.each do |game|
    .game
      %p= game.id
      = form_for(game, url: join_game_path(game), method: :put) do |f|
        = hidden_field_tag 'game[user_id]', current_user.id
        = f.submit 'Join', disabled: game.over? ? true: false, class: 'pure-button pure-button-primary'

  .games.margin10.margin-top-10
    = link_to 'Create a game', new_game_path

  .paginate.margin-top-10
    =will_paginate @games

app/views/games/new.html.haml
= form_for(@game, html: { class: 'pure-form pure-form-stacked' }) do |f|
  %fieldset
    = text_field_tag 'game[player_name]', nil, placeholder: 'Player Name'
    = f.submit class: 'button-secondary pure-button'

app/views/games/show.html.haml
.pure-u-1-3
  .pure-menu.player-menu
    .game{ data: { game: @game.id } }
    %ul.pure-menu-list
      %li.pure-menu-item
        #winner.winner
          - if @game.winner.present?
            %p#winner-name.winner-name= "Player: #{@game&.winner&.name} wins the game"

.pure-u-1-3
  %p#blockage-time.hidden{ data: { blockage_time: @game.blockage_time } }
  %p#clock.clock= @game.blockage_time
  %p#player.hidden{ data: { playerId: @player.id, colour: time_to_hex(@player.joined.to_i, @player.id)} }
  .squares.margin-top-10
    - @game.squares.ordered.each do |square|
      .square{ id: "square-#{square.id}",
               data: { colour: time_to_hex(@player.joined.to_i, @player.id), claimed: square.claimed?, unclaimed: square.claimed? ? false : true },
               style: square.claimed? ? "background: #{time_to_hex(@game.square_claimed_by(square.id)&.joined.to_i, @game.square_claimed_by(square.id)&.id)}" : '' }
        = form_for(square, url: claim_game_square_path(@game, square), method: :put) do |f|
          = hidden_field_tag 'square[player_id]', @player.id
          = f.submit square.number,
            disabled: !@game.started? || @game.over? || square.claimed?,
            class: 'square-button'
.pure-u-1-3
  .pure-menu.player-menu
    %ul.pure-menu-list.players#players
      - @players.each do |player|
        %li.pure-menu-item
          .pure-menu-link.player-menu-item{ style: "background: #{time_to_hex(player.joined.to_i, player.id)}" }
            %span.player-menu-item__name= player.name
            %span.player-menu-item__score.float-right{ id: "player-score-#{player.id}" }= @game.score(player.id)